# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('facebook_link', models.CharField(blank=True, max_length=250)),
                ('linkedin_link', models.CharField(blank=True, max_length=250)),
                ('adress', models.TextField(blank=True, max_length=500)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Area')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Division'),
        ),
        migrations.AddField(
            model_name='area',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.District'),
        ),
    ]
