# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviece_add',
            name='photo',
            field=models.ImageField(blank=True, upload_to='service_image'),
        ),
    ]
