# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180109_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serviece_add',
            new_name='Service_add',
        ),
    ]
