# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180110_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_add',
            name='provider',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
