# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180113_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_add',
            new_name='ServiceAdd',
        ),
        migrations.RenameModel(
            old_name='Service_catagory',
            new_name='ServiceCatagory',
        ),
    ]
